### PR TITLE
[droid-config-sailfish] move systemd service file for minui scaling

### LINKED ISSUE #25: storage encryption pinpad has large font
when i last reflashed my compact i decided to go for storage encryption, that introduced a new screen before device pin and sim pin need to be entered on boot. That pinpad hardly fits on the screen and has some overlapping going on.

I assume there must be some qml/css which needs a device specific size reduction for the compact.

Is anyone else also seeing that issue? Does anyone have a clue on what to look out for, to possibly patch my already flashed device and throw a patch on this repo?

### PR DESCRIPTION
**Pull request by henning-schild**
In recent versions systemd unit files need to live in /usr/lib not /lib.
Move them over to make the fix from
8bfd57f472e94f11c0bd88a4a61deb7f41055110 work again.

Closes: https://github.com/g7/sailfishx-patcher-f5321/issues/25
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
I could not actually test the package, or bump version ... or try and describe a runtime depends >= (whichever version of i.e. systemd), did not find the build system, spec files etc.

**Comment by henning-schild** [comment]
i am guessing https://github.com/sailfishos/systemd/commit/186b85031020f00cab3bcdc904d921546d282b1e changed things.

so we could rdep on ">=systemd-238" my device currently has `systemd-238+git6-1.10.2.jolla.armv7hl` installed

**Comment by g7** [comment]
Thanks for the patch! I think it's fine avoiding adding any dependencies - systemd supports loading from /usr/lib since a long time so it should work on older releases as well, plus jolla doesn't allow downloading of older releases anyways so it's unlikely that someone would want to patch an older zip.

Let me know what you think!

**Comment by henning-schild** [comment]
Well i just wanted to avoid that someone who the current version is working for might see a breaking change ... someone with an old device that did not see updates.
I think you can merge this. And in case you provide a pre-release i could test that. But in fact i hope it will just work ... just could not build myself and do that last bit of testing.

**Comment by g7** [comment]
Upgrades on existing (older) Sailfish OS installations should be fine - worst thing that can happen is the systemd unit not starting, but since it needs to adjust the symlink only one time it most likely has already done so previously.

Thanks again!

**Comment by henning-schild** [comment]
I have to thank you as well, for still maintaining this. While the device with sailfish has its limits, i really like the fact that such an old device really still is "supported".

**Comment by g7** [comment]
No problem, I actually don't use Sailfish OS anymore so I'm happy to merge changes by someone still interested in keeping this thing alive :) (and happy to see that it still works with very little maintenance)

By the way, it built: https://build.merproject.org/package/live_build_log/home:eugenio:compat-f5321/droid-compat-f5321/sailfish_latest_armv7hl/armv8el

So I think you could upgrade the device and check if it works :)

**Pull request merged**
